export const ESTADOS_USUARIO = {
    ACTIVO: 'ESTADO_ACTIVO',
    INACTIVO: 'ESTADO_INACTIVO',
    BLOQUEADO: 'ESTADO_BLOQUEADO'
};

export const ESTADOS_CATEGORIA = {
    ACTIVA: 'CAT_ACTIVA',
    INACTIVA: 'CAT_INACTIVA'
};

export const ESTADOS_PRODUCTO = {
    ACTIVO: 'PRO_ACTIVO',
    // INACTIVO: 'PRO_INACTIVA', // Eliminado de la BD
    AGOTADO: 'PRO_AGOTADO',      // Estado VISUAL (Calculado por stock)
    DESCONTINUADO: 'PRO_DESCONTINUADO'  // Estado BD
};