export const ESTADOS_USUARIO = {
    ACTIVO: 'ESTADO_ACTIVO',
    INACTIVO: 'ESTADO_INACTIVO',
    BLOQUEADO: 'ESTADO_BLOQUEADO'
};

export const ESTADOS_CATEGORIA = {
    ACTIVA: 'CAT_ACTIVA',
    INACTIVA: 'CAT_INACTIVA'
};

export const ESTADOS_PRODUCTO = {
    ACTIVO: 'PRO_ACTIVA',
    INACTIVO: 'PRO_INACTIVA',
    AGOTADO: 'PRO_AGOTADO',
    DESCONTINUADO: 'PRO_DESCONTINUADO'
};